server:
  port: 80
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    url: jdbc:mysql://39.100.6.47:3306/extension?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=TRUE
    username: jiuyao
    password: JiuYao123*
    driver-class-name: com.mysql.jdbc.Driver
#  redis:
    # Redis服务器连接端口
#    port: 6379
#    # Redis服务器地址
#    host: 127.0.0.1
#    database: 10
#    # 连接超时时间（毫秒）
#    timeout: 1000
#    jedis:
#      pool:
#        # 连接池最大连接数（使用负值表示没有限制）
#        max-idle: 200
#        # 连接池最大阻塞等待时间（使用负值表示没有限制）
#        max-wait: -1
  #对于rabbitMQ的支持
#  rabbitmq:
#    host: 127.0.0.1
#    port: 5672
#    username: guest
#    password: guest

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.jiuyao.boot


